<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * pollsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pollsRepository extends EntityRepository
{
}
